import type { CaptionCue, CaptionWord } from './segmentation'
import type { CaptionStylePreset } from '../constants'
import { formatAssTime } from '../utils/time'

/**
 * ASS subtitle document generation for FFmpeg burn-in.
 * PlayRes matches the render canvas (default 1080×1920) so font sizes in the
 * style presets (a % of height) map directly to ASS font size in px.
 */

function hexToAss(hex: string, opacity: number): string {
  const h = hex.replace('#', '')
  const r = h.slice(0, 2)
  const g = h.slice(2, 4)
  const b = h.slice(4, 6)
  // ASS alpha: 00 = opaque, FF = transparent
  const alpha = Math.round(255 * (1 - Math.min(1, Math.max(0, opacity))))
    .toString(16)
    .padStart(2, '0')
  return `&H${alpha}${b}${g}${r}`.toUpperCase()
}

/** ASS has no escape for braces — they would be parsed as override tags. */
function esc(text: string): string {
  return text.replace(/[{}]/g, '').replace(/\\/g, ' ').replace(/\s+/g, ' ').trim()
}

export interface AssBuildOptions {
  style: CaptionStylePreset
  fontSizePct?: number
  positionY?: number
  emphasis?: boolean
  uppercase?: boolean
  playResX?: number
  playResY?: number
  /** Style overrides from clip.captionOverrides (§26 preview/render parity). */
  textColor?: string
  highlightColor?: string
  boxOpacity?: number
  outlineWidth?: number
  shadow?: number
}

function fontNameFor(file: string): string {
  // Inter static TTFs register their weight in the family name; libass
  // matches by family name.
  if (file.includes('900Black')) return 'Inter Black'
  if (file.includes('800ExtraBold')) return 'Inter ExtraBold'
  if (file.includes('700Bold')) return 'Inter Bold'
  if (file.includes('600SemiBold')) return 'Inter SemiBold'
  return 'Inter'
}

/** Greedy word-wrap into lines by character budget. */
function wrapWords(words: CaptionWord[], maxChars: number): CaptionWord[][] {
  const lines: CaptionWord[][] = []
  let current: CaptionWord[] = []
  let len = 0
  for (const w of words) {
    if (len + w.text.length + 1 > maxChars && current.length > 0) {
      lines.push(current)
      current = []
      len = 0
    }
    current.push(w)
    len += w.text.length + 1
  }
  if (current.length) lines.push(current)
  return lines
}

export function buildAssDocument(cues: CaptionCue[], opts: AssBuildOptions): string {
  const W = opts.playResX ?? 1080
  const H = opts.playResY ?? 1920
  const style = opts.style

  const fontSize = Math.round(((opts.fontSizePct ?? style.fontSizePct) / 100) * H)
  const emphasis = opts.emphasis ?? style.emphasis
  const uppercase = opts.uppercase ?? style.uppercase
  const posY = Math.round((opts.positionY ?? style.positionY) * H)
  const fontFamily = fontNameFor(style.fontFile)

  // User overrides (clip-level) win over the template defaults.
  const textColor = opts.textColor ?? style.textColor
  const highlightColor = opts.highlightColor ?? style.highlightColor
  const boxOpacity = opts.boxOpacity !== undefined ? opts.boxOpacity : style.boxOpacity
  const outlineWidthOverride = opts.outlineWidth
  const shadowOverride = opts.shadow

  // Karaoke fill paints from Secondary → Primary, so with emphasis the
  // primary colour is the highlight; without emphasis both are plain text.
  const primary = hexToAss(emphasis ? highlightColor : textColor, 1)
  const secondary = hexToAss(textColor, 1)
  const outlineCol = hexToAss(style.outlineColor, 1)
  const useBox = boxOpacity > 0
  const back = hexToAss(style.boxColor, useBox ? boxOpacity : 0)
  const borderStyle = useBox ? 3 : 1
  const templateOutline = outlineWidthOverride !== undefined
    ? outlineWidthOverride
    : style.outlineWidth
  const outlineW = useBox ? Math.max(6, fontSize * 0.18) : Math.max(1, templateOutline * (fontSize / 70))
  const templateShadow = shadowOverride !== undefined ? shadowOverride : style.shadow
  const shadow = Math.max(0, templateShadow * (fontSize / 70))

  const header = [
    '[Script Info]',
    '; Generated by Clipwright Studio',
    'ScriptType: v4.00+',
    `PlayResX: ${W}`,
    `PlayResY: ${H}`,
    'WrapStyle: 2',
    'ScaledBorderAndShadow: yes',
    'YCbCr Matrix: TV.709',
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    `Style: Main,${fontFamily},${fontSize},${primary},${secondary},${outlineCol},${back},0,0,0,0,100,100,0,0,${borderStyle},${outlineW.toFixed(1)},${shadow.toFixed(1)},5,60,60,0,1`,
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'
  ]

  const events = cues.map((cue) => {
    const start = formatAssTime(cue.startTime)
    const end = formatAssTime(cue.endTime)
    let text: string

    if (emphasis && cue.words.length > 0) {
      // Word-level karaoke fill, wrapped into lines
      const lines = wrapWords(cue.words, style.maxCharsPerLine).slice(0, style.maxLines)
      text = lines
        .map((line) =>
          line
            .map((w) => {
              const cs = Math.max(1, Math.round((w.end - w.start) * 100))
              const t = esc(uppercase ? w.text.toUpperCase() : w.text)
              return `{\\kf${cs}}${t}`
            })
            .join(' ')
        )
        .join('\\N')
    } else {
      text = cue.lines
        .map((l) => esc(uppercase ? l.toUpperCase() : l))
        .join('\\N')
    }

    return `Dialogue: 0,${start},${end},Main,,0,0,0,,{\\pos(${Math.round(W / 2)},${posY})}${text}`
  })

  return [...header, ...events].join('\n') + '\n'
}
